<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="536" startPos="831" endPos="831" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Users\Matheus\Desktop\chat.io\index.js" backupFilePath="" originalFileLastModifTimestamp="1501377342" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="1" xOffset="0" scrollWidth="616" startPos="36" endPos="36" selMode="0" lang="HTML" encoding="-1" filename="C:\Users\Matheus\Desktop\chat.io\index.html" backupFilePath="" originalFileLastModifTimestamp="1501388297" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="5046312" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="432" startPos="269" endPos="269" selMode="0" lang="CSS" encoding="-1" filename="C:\Users\Matheus\Desktop\chat.io\public\css\style.css" backupFilePath="" originalFileLastModifTimestamp="1501392332" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="-1316506432" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="264" startPos="190" endPos="190" selMode="0" lang="JSON" encoding="-1" filename="C:\Users\Matheus\Desktop\chat.io\package.json" backupFilePath="" originalFileLastModifTimestamp="1501360919" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="104" startPos="37" endPos="37" selMode="0" lang="Batch" encoding="-1" filename="C:\Users\Matheus\Desktop\chat.io\start.bat" backupFilePath="" originalFileLastModifTimestamp="1501379862" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="6619238" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
